export const elements = [
    {
      atomicRadius: 37,
      ionRadius: '',
      vanDelWaalsRadius: 120,
      oxidationStates: '-1, 1',
    },
    {
      atomicRadius: 32,
      ionRadius: '',
      vanDelWaalsRadius: 140,
      oxidationStates: '',
    },
    {
      atomicRadius: 134,
      ionRadius: '76 (+1)',
      vanDelWaalsRadius: 182,
      oxidationStates: 1,
    },
    {
      atomicRadius: 90,
      ionRadius: '45 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: 82,
      ionRadius: '27 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 77,
      ionRadius: '16 (+4)',
      vanDelWaalsRadius: 170,
      oxidationStates: '-4, -3, -2, -1, 1, 2, 3, 4',
    },
    {
      atomicRadius: 75,
      ionRadius: '146 (-3)',
      vanDelWaalsRadius: 155,
      oxidationStates: '-3, -2, -1, 1, 2, 3, 4, 5',
    },
    {
      atomicRadius: 73,
      ionRadius: '140 (-2)',
      vanDelWaalsRadius: 152,
      oxidationStates: '-2, -1, 1, 2',
    },
    {
      atomicRadius: 71,
      ionRadius: '133 (-1)',
      vanDelWaalsRadius: 147,
      oxidationStates: -1,
    },
    {
      atomicRadius: 69,
      ionRadius: '',
      vanDelWaalsRadius: 154,
      oxidationStates: '',
    },
    {
      atomicRadius: 154,
      ionRadius: '102 (+1)',
      vanDelWaalsRadius: 227,
      oxidationStates: '-1, 1',
    },
    {
      atomicRadius: 130,
      ionRadius: '72 (+2)',
      vanDelWaalsRadius: 173,
      oxidationStates: '1, 2',
    },
    {
      atomicRadius: 118,
      ionRadius: '53.5 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 3',
    },
    {
      atomicRadius: 111,
      ionRadius: '40 (+4)',
      vanDelWaalsRadius: 210,
      oxidationStates: '-4, -3, -2, -1, 1, 2, 3, 4',
    },
    {
      atomicRadius: 106,
      ionRadius: '44 (+3)',
      vanDelWaalsRadius: 180,
      oxidationStates: '-3, -2, -1, 1, 2, 3, 4, 5',
    },
    {
      atomicRadius: 102,
      ionRadius: '184 (-2)',
      vanDelWaalsRadius: 180,
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 99,
      ionRadius: '181 (-1)',
      vanDelWaalsRadius: 175,
      oxidationStates: '-1, 1, 2, 3, 4, 5, 6, 7',
    },
    {
      atomicRadius: 97,
      ionRadius: '',
      vanDelWaalsRadius: 188,
      oxidationStates: '',
    },
    {
      atomicRadius: 196,
      ionRadius: '138 (+1)',
      vanDelWaalsRadius: 275,
      oxidationStates: 1,
    },
    {
      atomicRadius: 174,
      ionRadius: '100 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: 144,
      ionRadius: '74.5 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 136,
      ionRadius: '86 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 2, 3, 4',
    },
    {
      atomicRadius: 125,
      ionRadius: '79 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 2, 3, 4',
    },
    {
      atomicRadius: 127,
      ionRadius: '80 (+2*)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 139,
      ionRadius: '67 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, -2, -1, 1, 2, 3, 4, 5, 6, 7',
    },
    {
      atomicRadius: 125,
      ionRadius: '78 (+2*)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 126,
      ionRadius: '74.5 (+2*)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 1, 2, 3, 4, 5',
    },
    {
      atomicRadius: 121,
      ionRadius: '69 (+2)',
      vanDelWaalsRadius: 163,
      oxidationStates: '-1, 1, 2, 3, 4',
    },
    {
      atomicRadius: 138,
      ionRadius: '77 (+1)',
      vanDelWaalsRadius: 140,
      oxidationStates: '1, 2, 3, 4',
    },
    {
      atomicRadius: 131,
      ionRadius: '74 (+2)',
      vanDelWaalsRadius: 139,
      oxidationStates: 2,
    },
    {
      atomicRadius: 126,
      ionRadius: '62 (+3)',
      vanDelWaalsRadius: 187,
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 122,
      ionRadius: '73 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '-4, 1, 2, 3, 4',
    },
    {
      atomicRadius: 119,
      ionRadius: '58 (+3)',
      vanDelWaalsRadius: 185,
      oxidationStates: '-3, 2, 3, 5',
    },
    {
      atomicRadius: 116,
      ionRadius: '198 (-2)',
      vanDelWaalsRadius: 190,
      oxidationStates: '-2, 2, 4, 6',
    },
    {
      atomicRadius: 114,
      ionRadius: '196 (-1)',
      vanDelWaalsRadius: 185,
      oxidationStates: '-1, 1, 3, 4, 5, 7',
    },
    {
      atomicRadius: 110,
      ionRadius: '',
      vanDelWaalsRadius: 202,
      oxidationStates: 2,
    },
    {
      atomicRadius: 211,
      ionRadius: '152 (+1)',
      vanDelWaalsRadius: '',
      oxidationStates: 1,
    },
    {
      atomicRadius: 192,
      ionRadius: '118 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: 162,
      ionRadius: '90 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 148,
      ionRadius: '72 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 2, 3, 4',
    },
    {
      atomicRadius: 137,
      ionRadius: '72 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 2, 3, 4, 5',
    },
    {
      atomicRadius: 145,
      ionRadius: '69 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 156,
      ionRadius: '64.5 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, -1, 1, 2, 3, 4, 5, 6, 7',
    },
    {
      atomicRadius: 126,
      ionRadius: '68 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, 1, 2, 3, 4, 5, 6, 7, 8',
    },
    {
      atomicRadius: 135,
      ionRadius: '66.5 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 131,
      ionRadius: '59 (+1)',
      vanDelWaalsRadius: 163,
      oxidationStates: '2, 4',
    },
    {
      atomicRadius: 153,
      ionRadius: '115 (+1)',
      vanDelWaalsRadius: 172,
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 148,
      ionRadius: '95 (+2)',
      vanDelWaalsRadius: 158,
      oxidationStates: 2,
    },
    {
      atomicRadius: 144,
      ionRadius: '80 (+3)',
      vanDelWaalsRadius: 193,
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: 141,
      ionRadius: '112 (+2)',
      vanDelWaalsRadius: 217,
      oxidationStates: '-4, 2, 4',
    },
    {
      atomicRadius: 138,
      ionRadius: '76 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, 3, 5',
    },
    {
      atomicRadius: 135,
      ionRadius: '221 (-2)',
      vanDelWaalsRadius: 206,
      oxidationStates: '-2, 2, 4, 5, 6',
    },
    {
      atomicRadius: 133,
      ionRadius: '220 (-1)',
      vanDelWaalsRadius: 198,
      oxidationStates: '-1, 1, 3, 5, 7',
    },
    {
      atomicRadius: 130,
      ionRadius: '48 (+8)',
      vanDelWaalsRadius: 216,
      oxidationStates: '2, 4, 6, 8',
    },
    {
      atomicRadius: 225,
      ionRadius: '167 (+1)',
      vanDelWaalsRadius: '',
      oxidationStates: 1,
    },
    {
      atomicRadius: 198,
      ionRadius: '135 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: 169,
      ionRadius: '103.2 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '102 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '99 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '129 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '97 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: '',
      ionRadius: '122 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '117 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '93.8 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '92.3 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '1, 3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '107 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '90.1 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: '',
      ionRadius: '89 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: '',
      ionRadius: '103 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '102 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: 160,
      ionRadius: '86.1 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: 150,
      ionRadius: '71 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4',
    },
    {
      atomicRadius: 138,
      ionRadius: '72 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 2, 3, 4, 5',
    },
    {
      atomicRadius: 146,
      ionRadius: '66 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 159,
      ionRadius: '63 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, -1, 1, 2, 3, 4, 5, 6, 7',
    },
    {
      atomicRadius: 128,
      ionRadius: '63 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, -1, 1, 2, 3, 4, 5, 6, 7, 8',
    },
    {
      atomicRadius: 137,
      ionRadius: '68 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, -1, 1, 2, 3, 4, 5, 6',
    },
    {
      atomicRadius: 128,
      ionRadius: '86 (+2)',
      vanDelWaalsRadius: 175,
      oxidationStates: '2, 4, 5, 6',
    },
    {
      atomicRadius: 144,
      ionRadius: '137 (+1)',
      vanDelWaalsRadius: 166,
      oxidationStates: '-1, 1, 2, 3, 5',
    },
    {
      atomicRadius: 149,
      ionRadius: '119 (+1)',
      vanDelWaalsRadius: 155,
      oxidationStates: '1, 2, 4',
    },
    {
      atomicRadius: 148,
      ionRadius: '150 (+1)',
      vanDelWaalsRadius: 196,
      oxidationStates: '1, 3',
    },
    {
      atomicRadius: 147,
      ionRadius: '119 (+2)',
      vanDelWaalsRadius: 202,
      oxidationStates: '-4, 2, 4',
    },
    {
      atomicRadius: 146,
      ionRadius: '103 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '-3, 3, 5',
    },
    {
      atomicRadius: '',
      ionRadius: '94 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '-2, 2, 4, 6',
    },
    {
      atomicRadius: '',
      ionRadius: '62 (+7)',
      vanDelWaalsRadius: '',
      oxidationStates: '-1, 1, 3, 5',
    },
    {
      atomicRadius: 145,
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: '',
      ionRadius: '180 (+1)',
      vanDelWaalsRadius: '',
      oxidationStates: 1,
    },
    {
      atomicRadius: '',
      ionRadius: '148 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: 2,
    },
    {
      atomicRadius: '',
      ionRadius: '112 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: '',
      ionRadius: '94 (+4)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '104 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '3, 4, 5',
    },
    {
      atomicRadius: '',
      ionRadius: '102.5 (+3)',
      vanDelWaalsRadius: 186,
      oxidationStates: '3, 4, 5, 6',
    },
    {
      atomicRadius: '',
      ionRadius: '110 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '3, 4, 5, 6, 7',
    },
    {
      atomicRadius: '',
      ionRadius: '100 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '3, 4, 5, 6, 7',
    },
    {
      atomicRadius: '',
      ionRadius: '126 (+2)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4, 5, 6',
    },
    {
      atomicRadius: '',
      ionRadius: '97 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '96 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '95 (+3)',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3, 4',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '2, 3',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: 3,
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: 4,
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
    {
      atomicRadius: '',
      ionRadius: '',
      vanDelWaalsRadius: '',
      oxidationStates: '',
    },
  ];
  